### ISSUE TITLE
7.0环境报错android.os.FileUriExposedException: 7-29(2).apk exposed beyond app through Intent.getData()

### ISSUE THREAD

**Issue by fineemb** [parkingwang/next-version-android#1]
7.0环境报错android.os.FileUriExposedException: 7-29(2).apk exposed beyond app through Intent.getData()

**Comment by yoojia** [comment]
可以发详细的出错信息吗？

**Comment by chenxxpro** [comment]
可以发详细的出错信息吗？

**Comment by fineemb** [comment]
我已经更换了一个库,
具体原因我看了一下,就是7.0已经不能共享Uri了, 对于应用内直接打开APK是被禁止的.

2018-03-20 13:44 GMT+08:00 陈永佳 <notifications@github.com>:

**Comment by chenxxpro** [comment]
Soga，感谢你的反馈。我跟踪一下这个问题。
